/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicaveterinaria.vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author borch
 */
public class homeView extends javax.swing.JFrame {
   private boolean isLoggedIn = false;

    /**
     * Creates new form homeView
     */
    public homeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jTextField1 = new javax.swing.JTextField();
        jBIngresar = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 204, 204));
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText(" TEXTO BIENVENIDA ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 110, 50));

        jBIngresar.setText("Ingresar");
        jBIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngresarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jBIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngresarActionPerformed
        if (!isLoggedIn){
            showLoginDialog();
        }
    }//GEN-LAST:event_jBIngresarActionPerformed
    
    private void showLoginDialog(){
        JDialog loginDialog = new JDialog( this, "Iniciar sesión", true);
        loginDialog.setLayout(null);
        JTextField usernameField = new JTextField(20);
        JPasswordField passwordField = new JPasswordField(10);
        JButton showPasswordButton = new JButton("Ver");
        JButton loginButton = new JButton("Aceptar");
        JButton cancelButton = new JButton("Cancelar");
        
        // Etiquetas de usuario y contraseña
        JLabel userLabel = new JLabel("Usuario: ");
        JLabel passwordLabel = new JLabel("Contraseña: ");

        //Tamaño/diseño/ubicacion
        userLabel.setBounds(20, 20, 70, 20);
        usernameField.setBounds(100, 20, 150, 20);
        passwordLabel.setBounds(20, 50, 80, 20);
        passwordField.setBounds(100, 50, 150, 20);
        showPasswordButton.setBounds(260, 50, 70, 20);
        loginButton.setBounds(100, 80, 80, 30);
        cancelButton.setBounds(220, 80, 80, 30);

        
        // Lógica para mostrar/ocultar contraseña
        showPasswordButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (passwordField.getEchoChar() == '\u2022') {
                    passwordField.setEchoChar((char) 0);
                } else {
                    passwordField.setEchoChar('\u2022');
                }
            }
        });
                
        loginButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e){
                if (autenticacion(usernameField.getText(), new String(passwordField.getPassword()))) {
                    isLoggedIn = true;
                    JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso");
                    
                  // Determina si el usuario es Empleado o Veterinario
                 boolean isEmpleado = esEmpleado(usernameField.getText());  
                 
                 // Elimina el contenido actual del JFrame principal
                jDesktopPane1.removeAll();
                 
                // Agrega la ventana interna adecuada (Empleado o Veterinario)
                    if (isEmpleado) {
                        EmpleadoInternalFrame empleadoFrame = new EmpleadoInternalFrame();
                        jDesktopPane1.add(empleadoFrame);
                    } else {
                        VeterinarioInternalFrame veterinarioFrame = new VeterinarioInternalFrame();
                        jDesktopPane1.add(veterinarioFrame);
                    }
                    // Repinta el JFrame principal para mostrar la nueva ventana interna
                    jDesktopPane1.revalidate();
                    jDesktopPane1.repaint();
                 loginDialog.dispose();
                } else {
                    JOptionPane.showMessageDialog(loginDialog, "Usuario y/o contraseña incorrectas");
                }
            }
        });
        // Lógica para cerrar el cuadro de diálogo en el botón Cancelar
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                loginDialog.dispose();
            }
        });
        
        loginDialog.add(userLabel);
        loginDialog.add(usernameField);
        loginDialog.add(passwordLabel);
        loginDialog.add(passwordField);
        loginDialog.add(showPasswordButton);
        loginDialog.add(loginButton);
        loginDialog.add(cancelButton);

        loginDialog.setSize(360, 180);
        loginDialog.setLocationRelativeTo(this);
        loginDialog.setVisible(true);
        }
         private boolean autenticacion(String username, String password) {   
            String usuarioValido = "usuario";
            String contrasenaValida = "contraseña";
         
            if ("empleado@veterinaria.com".equals(username) && "@Empleado".equals(password)) {
                return true;
            } else if ("veterinario@veterinaria.com".equals(username) && "@VeteMed".equals(password)) {
                return true;
            } else{
                return false;
            }
         }
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIngresar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}